#!/usr/bin/ruby

require_relative "./virt-installer"

vm = VirtInstaller.new
# Personal work environment
vm.disk.dir      = "/space/libvirt/images"
vm.iso_dir       = "/space/iso"

# VM-specific settings
vm.name          = "CaaSP-Test-VM"
vm.disk.name     = "caasp-test-disk.qcow2"
vm.disk.size     = "39G"
vm.find_iso("*CaaS*") # Use the last matching one

# Detail flags - not strictly neccessary, might as well use defaults
vm.use_ssh       = true
vm.ssh_password  = "root"  # linuxrc will ask if not set (nil)
vm.use_multipath = false
vm.use_uefi      = false
vm.boot_insecure = true
# vm.use_vnc       = true
# vm.vnc_password  = "vnc"   # must specify password if use_vnc

# Uncomment to test invocation
# vm.dry_run = true

vm.start
